#define MAX_LINE_SIZE 81
#define MAX_REGESTER_SIZE 7
#define MAX_WORD_SIZE 14
#define MAX_LABEL_SIZE 31
#define OPCODE_SIZE 4
#define NUMBER_OF_ACTIONS 16
#define BINARY_CODE_SIZE 14
#define FOUR_CODE_SIZE 7
